### ISSUE TITLE
make contours on orthophoto maps black

### ISSUE THREAD

**Issue by gubuntu** [kartoza/SAGTA#12]

**Comment by seabilwe** [comment]
@NyakudyaA @gubuntu  Can this be closed because both the 20m and 5m contours for the orthophoto are already black

**Comment by NyakudyaA** [comment]
@seabilwe If you attach screenshots you can close

**Comment by seabilwe** [comment]
> @seabilwe If you attach screenshots you can close
![image](https://user-images.githubusercontent.com/56301949/115509329-97207d80-a27e-11eb-80eb-a10d576fa602.png)
