### ISSUE TITLE
improve contour style

### ISSUE THREAD

**Issue by gubuntu** [kartoza/SAGTA#13]
This will benefit all consumers of this layer, not just SAGTA

it's great that the 5m contours are rendering now. 

[topomaps_A3_landscape_orthophoto-6.pdf](https://github.com/kartoza/kartoza/files/4680057/topomaps_A3_landscape_orthophoto-6.pdf)

However, I think they are a bit intense and the labelling could be better. Why not use the topostyle version? 

Contour colour is fine, maybe thinner with a bit of transparency?

Contour label should be as close as possible to the real thing in colour and placement. NGI contours are digitised in the correct direction so in QGIS you can get them to face uphill. See if you can do that in SLD.

**Comment by seabilwe** [comment]
@NyakudyaA I made some mall changes to the contours, because the labeling does not look neat with the white buffer that I had initially done:

initial style:
![old style contour](https://user-images.githubusercontent.com/56301949/115679216-9f49ed00-a352-11eb-93f2-fb265ce9a78c.PNG)

current style:
![20m_contours](https://user-images.githubusercontent.com/56301949/115679303-b8eb3480-a352-11eb-9de6-357bc4322d81.PNG)
But I have not added them to geoserver yet.

[contour_styles.zip](https://github.com/kartoza/SAGTA/files/6356665/contour_styles.zip)

**Comment by NyakudyaA** [comment]
@seabilwe please check the name of the styles we are currently using and update them in geoserver

**Comment by seabilwe** [comment]
Okay @NyakudyaA

**Comment by seabilwe** [comment]
@NyakudyaA 20m contours have been styled
![image](https://user-images.githubusercontent.com/56301949/116370515-c6009b80-a80a-11eb-92fe-6ef89b60abaf.png)

**Comment by gubuntu** [comment]
contour labels should face uphill so if using QGIS you need to use these options. If the contours are all running in the same direction e.g. clockwise, like NGI contours are, then the labels will orient correctly. If you are using Geoserver I'm not sure if there are similar options yet. 
<img width="420" alt="Screenshot 2022-02-02 at 17 37 46" src="https://user-images.githubusercontent.com/496911/152186034-248d1707-01e7-4d48-aac8-c647602b499f.png"> and 
<img width="319" alt="Screenshot 2022-02-02 at 17 41 38" src="https://user-images.githubusercontent.com/496911/152186700-fd66e592-4481-4d16-bd76-2669061afa04.png">

**Comment by seabilwe** [comment]
@gubuntu, here is the current contour styling applied
1. 20 m contours
![image](https://user-images.githubusercontent.com/56301949/152314197-8adc0160-5cdf-4d8f-94a9-3f9f47b34bc7.png)
![image](https://user-images.githubusercontent.com/56301949/152314269-d9c8e857-228d-42be-b717-7f2625259e0b.png)

2. 5 m contours
![image](https://user-images.githubusercontent.com/56301949/152325826-7bbbd107-07e8-4240-8597-2f2739a22137.png)
![image](https://user-images.githubusercontent.com/56301949/152325892-174c1b18-7e91-4a43-a163-c0feb6e8316c.png)

**Comment by gubuntu** [comment]
LGTM
