### ISSUE TITLE
contours layers not showing

### ISSUE THREAD

**Issue by gubuntu** [kartoza/SAGTA#17]
I've changed the orthophoto theme to draw 5m contours for 1:10000 and to layer blend the NGI topo layer at smaller scales. 

However, in quite a few places I made maps in, there are no 5m contours. Are there really so few in SA or is the layer not working?

and the 20m contours do not draw at 1:10000  - do they have scale thresholds set on geoserver? Please enable them at 1:10000

**Comment by seabilwe** [comment]
@NyakudyaA I filtered the contours to be 10m
![image](https://user-images.githubusercontent.com/56301949/116360946-bda36300-a800-11eb-8e8a-1ba9135ea52d.png)

**Comment by gubuntu** [comment]
Why? 

Please draw whetever is in the 5m contour layer

**Comment by gubuntu** [comment]
closing since OP is redundant after split between hybrid and ortho, will open new issues re contours
