### ISSUE TITLE
fix favicon

### ISSUE THREAD

**Issue by gubuntu** [kartoza/SAGTA#19]
Kartoza logo for Kartoza sites

SAGTA logo for map downloader

**Comment by wolfbyne** [comment]
I guess this favicon is just being used from the lizmap-web-client image and needs to be changed their somehow...

**Comment by NyakudyaA** [comment]
Updated the nginx config on staging with the following
```
location ~* favicon|apple-touch-icon|android-chrome-|mstile-|safari-pinned-tab.svg|browserconfig.xml {
            root /srv/lizmap/www/;
        }
```
