### ISSUE TITLE
add magnetic declination arrow and explanation

### ISSUE THREAD

**Issue by gubuntu** [kartoza/SAGTA#20]
show true north and magnetic declination as closely as possible to the real toposheets

get the declination from https://www.ngdc.noaa.gov/geomag/calculators/help/declinationHelp.html for the current date and the centre coordinates of the map

annotate the declination arrow with the date and source

**Comment by Sickculture** [comment]
> Here is how I am going to get the Magnetic declination
> 
> From Lizmap - We are already getting the extent of the printed map. So we are going to do the following
> 
> * Get the centre of the map extent ( lat, long)
> * Pass these values into the QGIS Server script and then populate text box with these values.
> 
> ```
> import datetime
> import re
> import urllib.request
> import urllib.parse
> import json
> latitude=-30.460568
> longitude=23.446861
> now = datetime.datetime.now()
> month = now.month
> params = urllib.parse.urlencode({'lat1': latitude, 'lon1': longitude, 'resultFormat': 'json', 'startMonth': month})
> url = "http://www.ngdc.noaa.gov/geomag-web/calculators/calculateDeclination?%s" % params
> data = urllib.request.urlopen(url)
> response = data.read() 
> response_text = response.decode('utf-8')
> response_json = json.loads(response_text)
> ```
> 
> * Try to render the compass as used by the magnetic declination plugin

is it possible to get the magnetic bearing of a line with this script? I need a new field with the value of magnetic bearing in QGIS and Qfield. Perhaps you can help me?

**Comment by gubuntu** [comment]
no, magnetic declination is unrelated to bearing, unless you need it to adjust the true bearing of a line. So use other functions to get the true bearing, then add the declination to get the magnetic bearing.
