### ISSUE TITLE
activate print control on load

### ISSUE THREAD

**Issue by gubuntu** [kartoza/SAGTA#26]
Either the print control needs to be activated or it needs to be made very obvious that that is what needs to be activated by the user, and how to do so.

**Comment by NyakudyaA** [comment]
I have deployed this on staging. 
![Peek 2022-05-20 18-04](https://user-images.githubusercontent.com/2510900/169568298-e9be36af-c0cc-4915-870f-d81ff2d6500d.gif)

@gubuntu Should I deploy to production?

**Comment by gubuntu** [comment]
nice, I reckon. But ask on the WA group first

**Comment by gubuntu** [comment]
been deployed to production for a while
