### ISSUE TITLE
MD on the map downloader is too large

### ISSUE THREAD

**Issue by seabilwe** [kartoza/SAGTA#34]
![magt](https://user-images.githubusercontent.com/56301949/115507282-35f7aa80-a27c-11eb-84f6-a5904036ece0.jpeg)
![Attachment0](https://user-images.githubusercontent.com/56301949/115507284-37c16e00-a27c-11eb-9134-6d814f132f1d.jpeg)

**Comment by gubuntu** [comment]
Is the MD enabled in production? It needs to be in place asap for pro users

**Comment by seabilwe** [comment]
### Magnetic Declination Symbol
The MD symbol was designed using Inkscape, replicating the one in the NGI topomaps
![md_symbol2](https://user-images.githubusercontent.com/56301949/157260229-36d5aa70-e90e-4306-8e9f-bab40cb4c75b.png)
SVG: 
![md_symbol](https://user-images.githubusercontent.com/56301949/157260308-505528bd-aba3-47ea-aa5f-c7fe2463d004.svg)

### Magnetic Declination
To calculate the MD, the following script was used:
`import json
from datetime import datetime
from os import environ
from urllib import parse, request

from qgis.core import QgsMessageLog, Qgis, QgsExpression, QgsGeometry, QgsRectangle
from qgis.utils import qgsfunction



def json_response(url):
    data = request.urlopen(url)
    response = data.read()
    response_text = response.decode('utf-8')
    return response_text


@qgsfunction(args='auto', group='Kartoza')
def map_decl(center_lat, center_long, feature, parent):
    """
    Calculates the magnetic declination of the map centroid.
    <h2>Example usage:</h2>
    <ul>
      <li>map_decl(x(map_get( item_variables('Ortho'), 'map_extent_center')),y(map_get( item_variables('Ortho'), 'map_extent_center'))) </li>
      <li>map_decl('lat_centroid_function','long_centroid_function') </li>
    </ul>
    """
    # Calculate elevation from Geocontext
    elevation_url = "https://staging.geocontext.kartoza.com/api/v1/geocontext/value/group/%s/%s/elevation_group/?format=json" \
                    % (center_lat, center_long)
    print(elevation_url)
    elevation_response_text = json_response(elevation_url)
    elevation_response_json = json.loads(elevation_response_text)["service_registry_values"][0]
    elevation_value = elevation_response_json['value']
    now = datetime.now()
    month = now.month
    params = parse.urlencode({'lat1': center_lat, 'lon1': center_long, 'resultFormat': 'json', 'startMonth': month})
    mag_url = "http://www.ngdc.noaa.gov/geomag-web/calculators/calculateDeclination?%s" % params
    mag_response_text = json_response(mag_url)

    mag_response_json = json.loads(mag_response_text)["result"][0]
    magnetic_declination = mag_response_json["declination"]
    if center_lat > 0:
        lat_label = 'N'
    else:
        lat_label = 'S'
    if center_long > 0:
        long_label = 'E'
    else:
        long_label = 'W'

    formatted_label = '%s %s\n%s %s\n%s%s' % (
        lat_label, abs(center_lat), long_label, abs(center_long), 'Magnetic Declination ', magnetic_declination)

    return [lat_label, abs(center_lat), long_label, abs(center_long),  magnetic_declination, elevation_value]`

**To convert the values from decimal degrees to DMS, the following expression was applied:**

`concat (map_decl(x(map_get( item_variables('Ortho'), 'map_extent_center')),y(map_get( item_variables('Ortho'), 'map_extent_center')))[0], ' ',  to_dms(map_decl(x(map_get( item_variables('Ortho'), 'map_extent_center')),y(map_get( item_variables('Ortho'), 'map_extent_center')))[1], 'x', 2),

'\n',map_decl(x(map_get( item_variables('Ortho'), 'map_extent_center')),y(map_get( item_variables('Ortho'), 'map_extent_center')))[2], ' ', to_dms(map_decl(x(map_get( item_variables('Ortho'), 'map_extent_center')),y(map_get( item_variables('Ortho'), 'map_extent_center')))[3], 'x', 2), 

'\n', 'Elevation ', map_decl(x(map_get( item_variables('Ortho'), 'map_extent_center')),y(map_get( item_variables('Ortho'), 'map_extent_center')))[5], 

'\n','Magnetic declination ', map_decl(x(map_get( item_variables('Ortho'), 'map_extent_center')),y(map_get( item_variables('Ortho'), 'map_extent_center')))[3],'',to_dm(map_decl(x(map_get( item_variables('Ortho'), 'map_extent_center')),y(map_get( item_variables('Ortho'), 'map_extent_center')))[4],'x',0,'suffix'))`

### Output
![test map 2](https://user-images.githubusercontent.com/56301949/157266259-ce8b9fd7-abec-4a9e-8320-6fa5f96a63f6.png)

### Hurdle
The rendering of the map will become slow, therefore

**Comment by NyakudyaA** [comment]
@seabilwe I am going to deploy the plugin on the server and when you have the project ready you can save one i.e topomaps so that we can test

**Comment by seabilwe** [comment]
Okay @NyakudyaA

**Comment by seabilwe** [comment]
@NyakudyaA in the A3 landscape topo layout, I tried to change the name of the item variable, but it would still not pick up the feature in order to calculate the MD
![image](https://user-images.githubusercontent.com/56301949/157406091-3ed8d266-c68d-4571-8d25-9661e0abab65.png)

Then I used this initial expression to calculate the MD, which will give values in decimal degrees, but came to a similar outcome  
![image](https://user-images.githubusercontent.com/56301949/157406956-6a1bcbba-ec03-487b-81fc-c530a5c558dd.png)

I then went to creating a project with just the topo basemap, added it to a map, but still received the same outcome.

**Comment by seabilwe** [comment]
## Modified MD script

```
import json
from datetime import datetime
from os import environ
from urllib import parse, request
from math import floor
from qgis.core import QgsMessageLog, Qgis, QgsExpression, QgsGeometry, QgsRectangle
from qgis.utils import qgsfunction



def json_response(url):
    try:
        data = request.urlopen(url)
        error_code = data.getcode()
    except HTTPError as error:
        error_code = error.code
    if error_code == 200:
        response = data.read()
        response_text = response.decode('utf-8')
    else:
        response_text = None
    return response_text

def dd2dms(decimaldegree, direction='x'):
    if type(decimaldegree) != 'float':
        try:
            decimaldegree = float(decimaldegree)
        except:
            print ('\nERROR: Could not convert %s to float.'%(type(decimaldegree)))
            return 0
    if decimaldegree < 0:
        decimaldegree = -decimaldegree
        if direction == 'y':
            appendix = 'W'
        else:
            appendix = 'S'
    else:
        if direction == 'x':
            appendix = 'E'
        else:
            appendix = 'N'
    minutes = decimaldegree%1.0*60
    seconds = minutes%1.0*60
    dms_values = '{0}°{1}\'{2:2.3f}"{3}'.format(int(floor(decimaldegree)), int(floor(minutes)), seconds, appendix)
    
    return dms_values


@qgsfunction(args='auto', group='Kartoza')
def map_decl(center_lat, center_long, feature, parent):
    """
    Calculates the magnetic declination of the map centroid.
    <h2>Example usage:</h2>
    <ul>
      <li>map_decl(x(map_get( item_variables('Ortho'), 'map_extent_center')),y(map_get( item_variables('Ortho'), 'map_extent_center'))) </li>
      <li>map_decl('lat_centroid_function','long_centroid_function') </li>
    </ul>
    """
    # Calculate elevation from Geocontext
    elevation_url = "https://staging.geocontext.kartoza.com/api/v1/geocontext/value/group/%s/%s/elevation_group/?format=json" \
                    % (center_long, center_lat)
    elevation_response_text = json_response(elevation_url)
    if elevation_response_text is not None:
        elevation_response_json = json.loads(elevation_response_text)["service_registry_values"][0]
        elevation_value = elevation_response_json['value']
    else:
        elevation_value = 'None'
    now = datetime.now()
    month = now.month
    month_name = now.strftime('%B')
    month_day = now.day
    params = parse.urlencode({'lat1': center_lat, 'lon1': center_long, 'resultFormat': 'json', 'startMonth': month})
    mag_url = "http://www.ngdc.noaa.gov/geomag-web/calculators/calculateDeclination?%s" % params
    mag_response_text = json_response(mag_url)
    if mag_response_text is not None:
        mag_response_json = json.loads(mag_response_text)["result"][0]
        magnetic_declination = mag_response_json["declination"]

        if center_lat > 0:
            lat_label = 'S'
        else:
            lat_label = 'N'
        if center_long > 0:
            long_label = 'W'
        else:
            long_label = 'E'
        dms_center_lat = dd2dms(round(center_lat,4))
        dms_center_long = dd2dms(round(center_long,4))
        dms_magnetic_decl = dd2dms(round(magnetic_declination,4),direction='y')        
        formatted_label = '%s\n%s \n%s%s \n%s%s' % (dms_center_lat,  dms_center_long,'Elevation ',elevation_value, 'Magnetic Declination ', dms_magnetic_decl)
    else:
        formatted_label = None
        magnetic_declination = None
    
    
    return formatted_label
```
## Modified MD Expression
`map_decl(y(transform(map_get( item_variables('A3landscape'), 'map_extent_center'), 'EPSG:3857','EPSG:4326')),x(transform(map_get( item_variables('A3landscape'), 'map_extent_center'), 'EPSG:3857','EPSG:4326')))`

**Comment by NyakudyaA** [comment]
This has been fixed on the server. 
![render](https://user-images.githubusercontent.com/2510900/157828523-bd0998a6-08b1-4d5a-bf67-fefa46839bc8.png)

**Comment by NyakudyaA** [comment]
This has been resolved to specifications
![mag-decl](https://user-images.githubusercontent.com/2510900/167393909-15025d41-5837-47f6-a20c-0076557cf089.png)
