### ISSUE TITLE
Remove the black contours from the hybrid map

### ISSUE THREAD

**Issue by seabilwe** [kartoza/SAGTA#36]
- [ ]  The black contours on the hybrid map creates an offset effect, they must be removed. 

![image](https://user-images.githubusercontent.com/56301949/149313228-ff351f7c-bc4b-4a56-bc30-181ea3709ef4.png)

**Comment by seabilwe** [comment]
- Switched off the 20 m black contours and updated the hybrid map theme
![image](https://user-images.githubusercontent.com/56301949/149469994-35d3dbc8-8cb0-4990-8deb-9fdfb7be595e.png)
![image](https://user-images.githubusercontent.com/56301949/149470111-c5799667-e8e7-4ebf-92c4-9eda36c30018.png)


Offset effect removed
![image](https://user-images.githubusercontent.com/56301949/149470372-7d624098-1138-40a5-b2c8-20beef93b9e8.png)

**Comment by gubuntu** [comment]
the black contours are still in the hybrid map I just downloaded (see #37)

**Comment by NyakudyaA** [comment]
> the black contours are still in the hybrid map I just downloaded (see #37)

The latest project that have these changes is deployed here http://maps.kartoza.com:8084/. Can you confirm if the fixes are fine and I will deploy to the production

**Comment by seabilwe** [comment]
@NyakudyaA I am trying to print out a hybrid map (to check the fixes) from the link you provided (http://maps.kartoza.com:8084/) and there are no prints appearing to be downloaded.
![downloading-hybrid-map](https://user-images.githubusercontent.com/56301949/152308378-9a8a190b-eea0-4748-8436-1896537f2d7f.gif)

**Comment by seabilwe** [comment]
The black ortho contours have been removed from the hybrid map
![image](https://user-images.githubusercontent.com/56301949/152967677-6520a103-787d-40e8-a393-8c87157be070.png)
