### ISSUE TITLE
Remove red grid from hybrid map

### ISSUE THREAD

**Issue by seabilwe** [kartoza/SAGTA#37]
- [x] The hybrid map is not supposed to have a red grid that must be removed

**Comment by seabilwe** [comment]
- Red grid  have been removed from the hybrid map
![image](https://user-images.githubusercontent.com/56301949/149471515-474ca6d6-0581-4fff-909a-191badaf3a6f.png)
![A4 portrait hybrid](https://user-images.githubusercontent.com/56301949/149474058-3eed9f64-6243-4cd6-9443-8b3498755531.png)

**Comment by gubuntu** [comment]
the above is an ortho, not hybrid

**Comment by seabilwe** [comment]
The red grid has been removed from the hybrid map.

![image](https://user-images.githubusercontent.com/56301949/152967247-e354d08d-210c-4b59-b264-1c9c06ed028b.png)
