### ISSUE TITLE
remove all 1:10000 print option from hybrid maps

### ISSUE THREAD

**Issue by gubuntu** [kartoza/SAGTA#38]
the topo sheet layer does not render at 1:10000 so it is pointless offering a hybrid at that scale

**Comment by seabilwe** [comment]
1:10 000 print option for the hybrid map is removed cc @NyakudyaA 

![image](https://user-images.githubusercontent.com/56301949/152329010-f023a4a4-d5b3-441f-bca4-52cfc3d7fe62.png)

**Comment by seabilwe** [comment]
The 1:10000 scale option has been removed from the hybrid map layout
![image](https://user-images.githubusercontent.com/56301949/152968575-0fd8caed-9db3-4729-89ff-72b3a8c05e3d.png)

**Comment by gubuntu** [comment]
I think the 1:100k and 1:150k options should also be removed from the hybrid offering as the orthos don't look good at those scales, neither does the topo. Except that print scales are linked to the map scales, which will remove those options from the web map too, so maybe keep them, what do you think?

**Comment by NyakudyaA** [comment]
This has been fixed and deployed on staging.
