### ISSUE TITLE
papercuts from 9 Oct launch

### ISSUE THREAD

**Issue by gubuntu** [kartoza/SAGTA#5]
- [x] Make title box bigger or adaptive. Long titles get cut off (#610)
- [x] Anywhere latutides are shown as negative, they should instead show S
- [x] some templates still have ratio scale, scale bar and other items overlapping = messy
- [x] on of the A3 teamplates says ‘only 1:50000 on A4’. Check all of these

**Comment by NyakudyaA** [comment]
I have tried to set `QGIS_SERVER_SHOW_GROUP_SEPARATOR` but nothing comes up. So will leave this as a todo
