### ISSUE TITLE
Contours not appearing on Orthophoto map

### ISSUE THREAD

**Issue by seabilwe** [kartoza/SAGTA#53]
Update regarding the issue reported this morning
![image](https://user-images.githubusercontent.com/56301949/162963445-b8e7b1b1-7ed4-4c9d-8490-0a8285910149.png)

The layer styles for the 20 and 5 m contours were checked and everything is still intact.
https://maps.kartoza.com/geoserver/web/ seemed to have been down, Admire restarted the geoserver container on rancher, but it keeps going down. 
Admire is checking on the DB to see what might be causing this.

**Comment by seabilwe** [comment]
@gubuntu 

The rendering of the contours was tested in the staging https://staging.sagtamapdownloader.kartoza.com/index.php/view/map/?repository=kartoza&project=sagta_ortho. The contours are still not rendering. So far, https://maps.kartoza.com/geoserver/web/ is working okay. 

@NyakudyaA is testing the issue on his local machine.

**Comment by gubuntu** [comment]
So has this been resolved in the interim and if so how?

**Comment by NyakudyaA** [comment]
@seabilwe Is this still an issue?

**Comment by seabilwe** [comment]
@NyakudyaA, just printed an ortho map and it is no longer an issue
