### ISSUE TITLE
We need to restrict access for the profile tool

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/SAGTA#57]
# Problem
Currently, the profile tool is globally installed and accessible for both Pro and Lite users. We need to modify the code to restrict access based lizmap rights

![rights](https://user-images.githubusercontent.com/2510900/168619124-bc325533-57af-4b8d-bcc2-ac0646c1a722.png)

# Solution
Modify https://github.com/arno974/lizmap-altiProfil

**Comment by NyakudyaA** [comment]
This can be done using js expressions.

```
lizMap.events.on({
    'uicreated': function(e) {
        $('#mapmenu li.altiProfil').hide();
    }
});
```
@gubuntu Should I proceed to hide it for the Lite?

**Comment by gubuntu** [comment]
If you can, then please do so, but schedule for Monday to give a few days for Lite users to try it out

**Comment by NyakudyaA** [comment]
The profile tool is now only visible for the topo maps. I will remove access to the Lite-on Sunday night and close this

**Comment by gubuntu** [comment]
there's no reason to remove it from hybrid and orthophoto maps

**Comment by NyakudyaA** [comment]
Ok, will add it back there as well.

**Comment by NyakudyaA** [comment]
This is deployed with all required changes
