### ISSUE TITLE
Map downloader

### ISSUE THREAD

**Issue by bflouw** [kartoza/SAGTA#60]
Thanks for correcting the log-in. There is still an issue with the Lite version. It does not have the 1:50K map layer as an option under layers. The layer is there when selecting a print map but it is not visible as an option to the user.

**Comment by gubuntu** [comment]
@NyakudyaA @seabilwe the Lite version should look asactly like the Pro version. Why is it different? Please fix (and assign yourself, for some reason I can't assign you Seabilwer)

**Comment by seabilwe** [comment]
As Brandon mentioned, the topo sheet does not appear on startup for the Lite version, but when printing the map, the toposheet is printed out.
![image](https://user-images.githubusercontent.com/56301949/180432790-af2317b8-4427-4a3f-8b97-f24f80b7ca65.png)

On the LizMap config window, the topo sheet is saved as a base layer, similarly to the Pro version, it is not available on the site as an option in the baselayers. The map theme is still intact.
![image](https://user-images.githubusercontent.com/56301949/180433642-f97cbab1-120c-4a9c-9bcd-0b0175e3460a.png)
![image](https://user-images.githubusercontent.com/56301949/180433805-c455e8fa-5c05-4dd6-b47a-dfa428e108a9.png)

@NyakudyaA can you check what might be the problem. In the staging the lite version of the topo map is still okay

**Comment by gubuntu** [comment]
is this a bug? Has it been fixed? If so post a screenshot of the corrected situation and close

**Comment by seabilwe** [comment]
The bug has not been fixed yet.

@NyakudyaA, please have a look at this

**Comment by NyakudyaA** [comment]
Seems like the issue is because we need to upgrade lizmap and I will switch staging to production which is upgraded. Will add the login button first and then post when it's resolved

**Comment by NyakudyaA** [comment]
This is fixed
