### ISSUE TITLE
1:50K topo layer not shown on both Lite and Pro version of map downloader

### ISSUE THREAD

**Issue by bflouw** [kartoza/SAGTA#63]
I checked the map downloader today and noticed that the 1:50k topo layer is not visible to the user. It does render when you print a map but this defeats the purpose as users want to choose a specific area on the topo sheet and then print a map. Previously the index layer was displayed as a default overlay and when a topo map was printed the graticule would be printed in red in the centre of the map. While the graticule is useful to the user a note needs to be added on the default screen asking a user to click on the layers tool and then uncheck the graticule before printing.

**Comment by NyakudyaA** [comment]
Hi @bflouw, I am going to swap staging to the **production** shortly. The production needs to be upgraded to a new version t ofix that issue

**Comment by NyakudyaA** [comment]
![Selection_002](https://user-images.githubusercontent.com/2510900/182909791-40143c8f-9cbb-46d9-986e-9a5e9a674ae1.png)
