### ISSUE TITLE
Rendering of map in map downloader showing error and map not downloading

### ISSUE THREAD

**Issue by bflouw** [kartoza/SAGTA#64]
There is an error that shows up on the map alphanumerical grid when printing the map. There is also a network error when trying to download the printed map. This error occurs in both the lite and pro versions.

**Comment by seabilwe** [comment]
@bflouw I have tested the site on my end, and I am not getting any errors 
![replicating error](https://user-images.githubusercontent.com/56301949/182813742-f490d139-72e6-44f2-8354-2c43767d46c1.gif)

**Comment by bflouw** [comment]
Hi Abi 

Might be a network issue on my side. I managed to print the map and this is one of the errors - the alphanumeric grid is not aligned and the last label is given as an error. Please not attached. 

Regards, 

Brandon F. Louw
HOD Geography





M: +27 82 9275671
T:  +27 11 645 3052
E: ***@***.***

**Comment by seabilwe** [comment]
Hi, @bflouw I am not sure what could be causing the issue on your end. I printed it out from different browsers, but the issue you are having is not replicated on my side
![image](https://user-images.githubusercontent.com/56301949/182823058-2a444839-9b42-47a3-8f0e-a50996a699e6.png)

**Comment by seabilwe** [comment]
@NyakudyaA can you also try to print

**Comment by NyakudyaA** [comment]
You need to enable popus
