### ISSUE TITLE
Adjust position of the MD

### ISSUE THREAD

**Issue by seabilwe** [kartoza/SAGTA#74]
![image](https://user-images.githubusercontent.com/56301949/215478939-7f595bad-ecda-4d8a-ac58-94253fcbc117.png)

**Comment by seabilwe** [comment]
The position of the MD has been adjusted: 
![image](https://github.com/kartoza/SAGTA/assets/56301949/94af0cc7-3cc6-408b-8de9-572da40590cd)

**Comment by gubuntu** [comment]
the W is still wrapping, please fix

**Comment by NyakudyaA** [comment]
@seabilwe Did you get this fixed again ?

**Comment by seabilwe** [comment]
Yes this is fixed:
![image](https://github.com/kartoza/SAGTA/assets/56301949/d34ab32f-32bb-4ea2-afac-99c5c2613935)
