### ISSUE TITLE
Polish magnetic declination presentation

### ISSUE THREAD

**Issue by gubuntu** [kartoza/SAGTA#78]
- left justify
- remove spaces within each ordinate or otherwise make sticky spaces so the ordinate doesn't wrap, or nicely placed newlines
- remove 'per year' (because 'annual' already says that)

<img width="271" alt="Screenshot 2023-05-29 at 10 40 54" src="https://github.com/kartoza/SAGTA/assets/496911/3820270d-4ebd-42ca-9bba-85dde1903d64">

**Comment by seabilwe** [comment]
The MD text has been fixed
![image](https://github.com/kartoza/SAGTA/assets/56301949/c62c0489-6790-4a66-8b4e-f1cde12a71d9)
