### ISSUE TITLE
add CRS info to maps

### ISSUE THREAD

**Issue by gubuntu** [kartoza/SAGTA#79]
Text like this needs to go on each map, maybe in the existing text block

"CRS: Spherical Mercator. Distances unreliable."

If there's space, you could do something longer like

"CRS: Spherical Mercator (EPSG:3857), NOT Transverse Mercator. Measured distances are unreliable."

Check on the WhatsApp group to get the text right before implementing.

**Comment by NyakudyaA** [comment]
This is added, @seabilwe Did you add this already
![image](https://github.com/kartoza/SAGTA/assets/2510900/b710aa29-298c-45a3-83af-78680b6b489d)

**Comment by seabilwe** [comment]
Yes I did @NyakudyaA. 

I think we can close the ticket.
