### ISSUE TITLE
The downloaded printed map is empty

### ISSUE THREAD

**Issue by seabilwe** [kartoza/SAGTA#81]
The printed map product, downloads an empty map

![map-product-empty](https://github.com/kartoza/SAGTA/assets/56301949/18d3d729-b868-4537-8c52-6084d72a31fd)

**Comment by NyakudyaA** [comment]
@seabilwe Can you try again

**Comment by seabilwe** [comment]
@NyakudyaA 

The downloaded printed map is now available.
![image](https://github.com/kartoza/SAGTA/assets/56301949/9418eb5c-3a67-43c8-8a59-c90f98a4eea6)
