### ISSUE TITLE
Login details, not allowing  user to login

### ISSUE THREAD

**Issue by seabilwe** [kartoza/SAGTA#82]
When logging in to access the other map projects, the interface does not allow the login to go through.

![password-not-allowing-log-in](https://github.com/kartoza/SAGTA/assets/56301949/f055cc92-2291-43c0-abf3-3fe5e0e49502)

**Comment by NyakudyaA** [comment]
@seabilwe You do not need to log in using connect. That's for admins on the downloader. You need to use the other button. If you need to use the first option make sure your credentials are corect

**Comment by seabilwe** [comment]
Okay, it works okay, but it's funny that I used Connect often to access the other projects.

But I was able to login
